name: macOS

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  build:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: brew install re2c p7zip cmake

    - name: Build ninja
      shell: bash
      env:
        MACOSX_DEPLOYMENT_TARGET: 10.15
      run: |
        cmake -GXcode -Bbuild-arm64 '-DCMAKE_OSX_ARCHITECTURES=arm64'
        cmake -GXcode -Bbuild-x86_64 '-DCMAKE_OSX_ARCHITECTURES=x86_64'
        cmake --build build-arm64 --config Release
        cmake --build build-x86_64 --config Release

    - name: Test ninja (arm64)
      run: ctest -C Release -vv
      working-directory: build-arm64
      
    - name: Test ninja (x86_64)
      run: ctest -C Release -vv
      working-directory: build-x86_64

    - name: Create ninja archive (arm64)
      shell: bash
      run: |
        mkdir artifact
        7z a artifact/ninja-mac-arm64.zip ./build-arm64/Release/ninja
    
    - name: Create ninja archive (x86_64)
      shell: bash
      run: |
        mkdir artifact
        7z a artifact/ninja-mac-x86_64.zip ./build-x86_64/Release/ninja

    # Upload ninja binary archives as an artifacts
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ninja-binary-archives
        path: artifact

    - name: Upload release asset (arm64)
      if: github.event.action == 'published'
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./artifact/ninja-mac-arm64.zip
        asset_name: ninja-mac-arm64.zip
        asset_content_type: application/zip
        
    
    - name: Upload release asset (x86_64)
      if: github.event.action == 'published'
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./artifact/ninja-mac-x86_64.zip
        asset_name: ninja-mac-x86_64.zip
        asset_content_type: application/zip
