name: macOS

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: brew install re2c p7zip cmake sccache
      
    - name: Cache C/C++ Build Results
      uses: actions/cache@v3
      with:
        path: /Users/runner/Library/Caches/Mozilla.sccache
        key: ${{ runner.os }}-sccache
      
    - name: Generate Ninja
      shell: bash
      env:
        MACOSX_DEPLOYMENT_TARGET: 10.15
      run: |
        cmake -Bbuild '-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64' -DCMAKE_CXX_COMPILER_LAUNCHER=sccache -DCMAKE_C_COMPILER_LAUNCHER=sccache

    - name: Build ninja
      shell: bash
      env:
        MACOSX_DEPLOYMENT_TARGET: 10.15
        SCCACHE_CACHE_MULTIARCH: 1
      run: |
        cmake --build build --config Release
        
    - name: Dump sccache stats (after)
      shell: bash
      env:
        SCCACHE_CACHE_MULTIARCH: 1
      run: sccache --show-stats

    - name: Test ninja
      run: ctest -C Release -vv
      working-directory: build
    
    - name: Create ninja archive
      shell: bash
      run: |
        mkdir artifact
        7z a artifact/ninja-mac.zip ./build/ninja

    # Upload ninja binary archives as an artifacts
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ninja-binary-archives
        path: artifact

    - name: Upload release asset
      if: github.event.action == 'published'
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./artifact/ninja-mac.zip
        asset_name: ninja-mac.zip
        asset_content_type: application/zip

